##
# Drupal/SSH with Nginx, PHP5 and SQLite
##
FROM ubuntu:trusty
MAINTAINER http://www.github.com/b7alt/ by b7alt


ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update 
RUN apt-get upgrade -y
RUN apt-get install -y supervisor openssh-server nginx php5-fpm php5-sqlite php5-gd emacs php-apc 

RUN apt-get install -y mysql-server mysql-client php5-mysql

RUN update-rc.d nginx disable
RUN update-rc.d php5-fpm disable
RUN update-rc.d supervisor disable
RUN update-rc.d mysql disable
RUN update-rc.d ssh disable

EXPOSE 22 80

# Drush install with pear
RUN apt-get install -y php-pear
RUN pear channel-discover pear.drush.org 
RUN pear install drush/drush
RUN drush version
RUN pear upgrade drush/drush



RUN mkdir -p /var/run/sshd /srv/drupal/www /srv/drupal/config /srv/data /srv/logs /tmp

ADD site.conf /srv/drupal/config/site.conf
ADD nginx.conf /nginx.conf
ADD php-fpm.conf /php-fpm.conf
ADD supervisord.conf /supervisord.conf
ADD settings.php.append /settings.php.append

# php5-apc
RUN sed -i '$a apc.shm_size=128M' /etc/php5/conf.d/20-apc.ini
RUN sed -i '$a apc.include_once_override=0' /etc/php5/conf.d/20-apc.ini

# php parameters
RUN sed -i 's|max_execution_time = 30|max_execution_time = 180 |g' /etc/php5/fpm/php.ini
RUN sed -i 's|memory_limit = 128M|memory_limit = 256M|g' /etc/php5/fpm/php.ini


RUN mysqladmin -u root password $DRUPAL_PASSWORD

RUN mysql -uroot -pdrupal -e "CREATE DATABASE www80; GRANT ALL PRIVILEGES ON www80.* TO 'drupal'@'localhost' IDENTIFIED BY '$DRUPAL_PASSWORD'; FLUSH PRIVILEGES;"





RUN cd /tmp && drush dl commons && mv /tmp/commons*/* /srv/drupal/www/ && rm -rf /tmp/*
RUN chmod a+w /srv/drupal/www/sites/default && mkdir /srv/drupal/www/sites/default/files
RUN chown -R www-data:www-data /srv/drupal/www/
RUN cp /srv/drupal/www/sites/default/default.settings.php /srv/drupal/www/sites/default/settings.php
RUN chmod a+w /srv/drupal/www/sites/default/settings.php
RUN chown www-data:www-data /srv/data


RUN chmod a+w /srv/drupal/www/sites/default/files
#RUN cd /srv/drupal/www/ && drush -y site-install standard --account-name=admin --account-pass=test --db-url=sqlite:sites/default/files/.ht.sqlite

RUN cat /settings.php.append >> /srv/drupal/www/sites/default/settings.php


RUN echo "root:root" | chpasswd

ENTRYPOINT [ "/usr/bin/supervisord", "-n", "-c", "/supervisord.conf", "-e", "trace" ]
